# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-20.04

steps:
- script: |
     python --version
     go version 
  displayName: 'Check & Prepare Environment'
- script: python -m unittest
  displayName: 'Run All test'

